### ISSUE TITLE
Background image is distortion, and  it should load full image

### ISSUE THREAD

**Issue by thuypt** [prithivraj/Surveys#18]
<img src="https://user-images.githubusercontent.com/6264092/37386700-1c50148c-278c-11e8-879a-434516fbc893.png" height="308" width="200" >

**Comment by prithivraj** [comment]
Two things here.

1. The document said 
> To get the high resolution image just append “l” to the image url you obtain in the API response

This is the URL I got in the response. 
https://dhdbhh0jsld0o.cloudfront.net/m/1ea51560991bcb7d00d0_
Appending "I" to it does not return a full resolution image.

2. I've fixed the distortion. The image now maintains aspect ratio but looks blurry because it's not full resolution.

**Comment by thuypt** [comment]
With your cover image, this is high resolution url 
https://dhdbhh0jsld0o.cloudfront.net/m/1ea51560991bcb7d00d0_l
it works fine, please recheck.

**Comment by prithivraj** [comment]
fixed by https://github.com/prithivraj/Surveys/pull/22

@thuypt I had put an i instead of a L. Works fine now, thanks.

**Comment by sleepylee** [comment]
just an extra information: the `l` stands for `large`, our api designed to provide other different size of image to suit on different purposes too ('m' for medium & 's' for small are the available options too) :-)
